import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { Layout } from "@/layouts/Layout";

export default function Home() {
  return (
    <Layout title="Create Next App">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Welcome to cloud storage!</h1>
      </main>
    </Layout>
  );
}
