import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import { Layout } from "@/layouts/Layout";
import { checkAuth } from "@/utils/checkAuth";
import { GetServerSidePropsContext } from "next";

const inter = Inter({ subsets: ["latin"] });

// type HomeProps = {
//   isAuthenticated: boolean;
// };

export default function Home() {
  return (
    <Layout title="Create Next App">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Welcome to cloud storage!</h1>
      </main>
    </Layout>
  );
}

// export async function getServerSideProps(ctx: GetServerSidePropsContext) {
//   const authResult = await checkAuth(ctx);

//   if ("props" in authResult) {
//     return {
//       props: {
//         isAuthenticated: true,
//       },
//     };
//   } else if ("redirect" in authResult) {
//     return {
//       redirect: authResult.redirect,
//     };
//   }
// }
